### ISSUE TITLE
Here is another approach worth documenting

### ISSUE THREAD

**Issue by zjt** [renisac/O365-Management-and-Log-Scripts#19]
https://journeyofthegeek.com/2019/01/30/capturing-and-visualizing-office-365-security-logs-part-1/
https://github.com/mattfeltonma/lambda-azureadlogs

**Comment by mdavis332** [comment]
heya @zjt, do you feel like [REFS.md](https://github.com/renisac/O365-Management-and-Log-Scripts/blob/master/REFS.md) is an appropriate place to link those from? you wanna give a go at a PR?

**Comment by mdavis332** [comment]
@zjt I'm sure it's a crazy time for you, but let me know if you're interested in working up a PR for your suggestion.

> heya @zjt, do you feel like [REFS.md](https://github.com/renisac/O365-Management-and-Log-Scripts/blob/master/REFS.md) is an appropriate place to link those from? you wanna give a go at a PR?

**Comment by mdavis332** [comment]
Resolved in 32ac53588884483da374a7d4599066776eb7539f
